-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 09:00:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema warpfiy_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `warpfiy_db` ;

-- -----------------------------------------------------
-- Schema warpfiy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `warpfiy_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `warpfiy_db` ;

-- -----------------------------------------------------
-- Table `warpfiy_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_db`.`usuario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(180) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_usuario_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_db`.`papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_db`.`papel` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_papel_nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_db`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_db`.`permissao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `recurso` VARCHAR(100) NOT NULL COMMENT 'alvo da permissão, o objeto/entidade que será manipulado, exemplo: pedido, usuario, relatorio_gerencial',
  `acao` VARCHAR(50) NOT NULL COMMENT 'Representa \"o que pode ser feito\" no recurso, Exemplos:\n criar, \nler\n, atualizar, \ndeletar, \naprovar, \ncancelar\n, exportar',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_permissao_nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_db`.`usuario_papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_db`.`usuario_papel` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT UNSIGNED NOT NULL,
  `papel_id` BIGINT UNSIGNED NOT NULL,
  `data_inicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_fim` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_papel_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_papel_papel_idx` (`papel_id` ASC) VISIBLE,
  UNIQUE INDEX `uk_usu_pap_usuario_id_papel_id` (`usuario_id` ASC, `papel_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_papel_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `warpfiy_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_papel_papel`
    FOREIGN KEY (`papel_id`)
    REFERENCES `warpfiy_db`.`papel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_db`.`papel_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_db`.`papel_permissao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `papel_id` BIGINT UNSIGNED NOT NULL,
  `permissao_id` BIGINT UNSIGNED NOT NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_papel_permissao_papel_idx` (`papel_id` ASC) VISIBLE,
  INDEX `fk_papel_permissao_permissao_idx` (`permissao_id` ASC) VISIBLE,
  UNIQUE INDEX `uk_pap_per_papel_id_permissao_id` (`papel_id` ASC, `permissao_id` ASC) VISIBLE,
  CONSTRAINT `fk_papel_permissao_papel`
    FOREIGN KEY (`papel_id`)
    REFERENCES `warpfiy_db`.`papel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_papel_permissao_permissao`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `warpfiy_db`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_db`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_db`.`pessoa` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT UNSIGNED NOT NULL,
  `nome_completo` VARCHAR(150) NOT NULL,
  `nome_social` VARCHAR(100) NULL,
  `cpf` VARCHAR(14) NULL,
  `rg` VARCHAR(14) NULL,
  `telefone_movel` VARCHAR(100) NULL,
  `telefone_fixo` VARCHAR(100) NULL,
  `logradouro_nome` VARCHAR(100) NULL,
  `numero_endereco` VARCHAR(100) NULL,
  `bairro_distrito` VARCHAR(100) NULL,
  `localidade_uf` VARCHAR(100) NULL,
  `cep` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `warpfiy_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- junção
-- -----------------------------------------------------
-- Table `warpfiy_bd`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_bd`.`evento` (
  `idcard` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(50) NOT NULL,
  `titulo` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `sub_descricao` VARCHAR(50) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(50) NOT NULL,
  `endereco_idendereco` BIGINT NOT NULL,
  `pessoa_idPessoa` BIGINT NOT NULL,
  PRIMARY KEY (`idcard`),
  INDEX `fk_evento_pessoa1_idx` (`pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_evento_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `warpfiy_bd`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_bd`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_bd`.`imagens` (
  `idimagens` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `data_upload` DATETIME NOT NULL,
  `evento_id` BIGINT UNSIGNED NULL,
  `pessoa_idPessoa` BIGINT NOT NULL,
  PRIMARY KEY (`idimagens`),
  INDEX `fk_imagens_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_imagens_Pessoa1_idx` (`pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_imagens_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `warpfiy_bd`.`evento` (`idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagens_Pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `warpfiy_bd`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_bd`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_bd`.`notificacao` (
  `idnotificacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `destino` VARCHAR(512) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `pessoa_idPessoa_notificada` BIGINT NOT NULL COMMENT 'Id da pessoa a ser notificada pelo Organizador',
  `pessoa_idPessoa_organizador` BIGINT NOT NULL COMMENT 'Id do Organizador que fará a notificação para o Colaborador',
  PRIMARY KEY (`idnotificacao`),
  INDEX `fk_notificacao_pessoa1_idx` (`pessoa_idPessoa_notificada` ASC) VISIBLE,
  INDEX `fk_notificacao_pessoa2_idx` (`pessoa_idPessoa_organizador` ASC) VISIBLE,
  CONSTRAINT `fk_notificacao_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa_notificada`)
    REFERENCES `warpfiy_bd`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_pessoa2`
    FOREIGN KEY (`pessoa_idPessoa_organizador`)
    REFERENCES `warpfiy_bd`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpfiy_bd`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warpfiy_bd`.`avaliacao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evento_id` BIGINT UNSIGNED NOT NULL,
  `avaliacao` TEXT NULL,
  `estrelas` INT NULL DEFAULT 1 COMMENT 'Quantidade de estrelas da avaliação: 1 - Ruim...5-Excelente',
  `pessoa_idPessoa` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacao_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_avaliacao_pessoa1_idx` (`pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `warpfiy_bd`.`evento` (`idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `warpfiy_bd`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
