-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 09:29:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema warpify
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `warpify` ;

-- -----------------------------------------------------
-- Schema warpify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `warpify` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `warpify` ;

-- -----------------------------------------------------
-- Table `warpify`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`permissao` ;

CREATE TABLE IF NOT EXISTS `warpify`.`permissao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `recurso` VARCHAR(100) NOT NULL,
  `acao` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`papel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`papel` ;

CREATE TABLE IF NOT EXISTS `warpify`.`papel` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`papel_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`papel_permissao` ;

CREATE TABLE IF NOT EXISTS `warpify`.`papel_permissao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `permissao_id` BIGINT UNSIGNED NOT NULL,
  `papel_id` BIGINT UNSIGNED NOT NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_papel_permissao_permissao1_idx` (`permissao_id` ASC),
  INDEX `fk_papel_permissao_papel1_idx` (`papel_id` ASC),
  CONSTRAINT `fk_papel_permissao_permissao1`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `warpify`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_papel_permissao_papel1`
    FOREIGN KEY (`papel_id`)
    REFERENCES `warpify`.`papel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`usuario` ;

CREATE TABLE IF NOT EXISTS `warpify`.`usuario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `ativo` TINYINT NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`usuario_papel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`usuario_papel` ;

CREATE TABLE IF NOT EXISTS `warpify`.`usuario_papel` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT UNSIGNED NOT NULL,
  `papel_id` BIGINT UNSIGNED NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_papel_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_usuario_papel_papel1_idx` (`papel_id` ASC),
  CONSTRAINT `fk_usuario_papel_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `warpify`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_papel_papel1`
    FOREIGN KEY (`papel_id`)
    REFERENCES `warpify`.`papel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `warpify`.`pessoa` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT UNSIGNED NOT NULL,
  `nome_completo` VARCHAR(100) NULL,
  `cpf` INT(14) NULL,
  `telefone` INT(20) NULL,
  `estado` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `lote` VARCHAR(100) NULL,
  `cep` INT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_pessoa_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `warpify`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`notificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`notificacao` ;

CREATE TABLE IF NOT EXISTS `warpify`.`notificacao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `destino` VARCHAR(100) NOT NULL,
  `data_criacao` VARCHAR(100) NOT NULL,
  `pessoa_id_notificador` BIGINT UNSIGNED NOT NULL,
  `pessoa_id_recebedor` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notificacao_pessoa1_idx` (`pessoa_id_notificador` ASC),
  INDEX `fk_notificacao_pessoa2_idx` (`pessoa_id_recebedor` ASC),
  CONSTRAINT `fk_notificacao_pessoa1`
    FOREIGN KEY (`pessoa_id_notificador`)
    REFERENCES `warpify`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_pessoa2`
    FOREIGN KEY (`pessoa_id_recebedor`)
    REFERENCES `warpify`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`evento` ;

CREATE TABLE IF NOT EXISTS `warpify`.`evento` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pessoa_id` BIGINT UNSIGNED NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `ativo` TINYINT NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `lote` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_evento_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `warpify`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `warpify`.`avaliacao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pessoa_id` BIGINT UNSIGNED NOT NULL,
  `evento_id` BIGINT UNSIGNED NOT NULL,
  `estrela` INT NOT NULL,
  `avaliacao` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacao_evento1_idx` (`evento_id` ASC),
  INDEX `fk_avaliacao_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_avaliacao_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `warpify`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `warpify`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warpify`.`galeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warpify`.`galeria` ;

CREATE TABLE IF NOT EXISTS `warpify`.`galeria` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `caminho` VARCHAR(100) NOT NULL,
  `data_upload` DATETIME NOT NULL,
  `pessoa_id` BIGINT UNSIGNED NOT NULL,
  `evento_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_galeria_evento1_idx` (`evento_id` ASC),
  CONSTRAINT `fk_galeria_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `warpify`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_galeria_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `warpify`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
